### PR TITLE
Allow getters for synthetic primary keys

### PR DESCRIPTION
**Pull request by demands**
i.e., if you have a resource that looks like this:

```js
var resource = new ResourceSchema(Model, {primaryKey: 'foo.bar'})
```

then you should be able to do something like this:

```js
app.get('/resource/:primaryKey', resource.get('primaryKey'))
```

And have `GET /resource/quux` do a query like `Model.find('foo:bar': 'quux')`.

### CODE REVIEW

**Comment by demands** [comment]
Example of this in action: https://github.com/goodeggs/domain-events-app/blob/master/web/v1/domain_events/index.coffee#L5

**Comment by dannynelson** [comment]
Looks good to me. Thanks Max! Feel free to merge when ready

**Comment by dannynelson** [comment]
If you could add a note to the options section of the README too, that would be awesome :)

**Comment by demands** [comment]
I was looking for where in the readme a description of the feature would go, but it looks like you already summed it up pretty nicely in the description of the get(idField) method:

> ### get(idField)
> 
> - **idField** - field to use as resource identifier. Note, this must match the field name defined on the resource and the name on req.params.

**Pull request merged**
